export enum i18Chunks {
  TRANSLATION = 'translation',
  HEADER = 'header',
  PROFILE = 'profile',
  TAGS = 'tags',
}

export enum i18Keys {
  CLOSE = 'CLOSE',
  REFRESH_PAGE = 'REFRESH_PAGE',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ADMIN = 'ADMIN',
  USER = 'USER',
  WAIT = 'WAIT',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',
  TAGS = 'TAGS',
  SEARCH = 'SEARCH',
  FIND = 'FIND',
  MY_SUBSCRIPTIONS = 'MY_SUBSCRIPTIONS',
  BLACK_LIST = 'BLACK_LIST',
  ALL = 'ALL',
  BLOCK = 'BLOCK',
  UNBLOCK = 'UNBLOCK',
  POSTS = 'POSTS',
  LOG_IN = 'LOG_IN',
  NOT_FOUND = 'NOT_FOUND',
  SUBSCRIBERS = 'SUBSCRIBERS',
  CREATE_POST = 'CREATE_POST',
  LOG_OUT = 'LOG_OUT',
  HIDE = 'HIDE',
  SEND_REPORT = 'SEND_REPORT',
  DELETE = 'DELETE',
}

export enum i18KeysHeader {
  MAIN_PAGE = 'MAIN_PAGE',
  ABOUT_PROJECT = 'ABOUT_PROJECT',
  PROFILE = 'PROFILE',
  TAGS = 'TAGS',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  ADMIN = 'ADMIN',
}

export enum i18Tags {
  ANIMALS = 'ANIMALS',
  HUMOR = 'HUMOR',
  TECHNOLOGIES = 'TECHNOLOGIES',
  MOVIES = 'MOVIES',
  SPORT = 'SPORT',
}

export enum i18KeysProfile {
  REGISTRATION_DATE = 'REGISTRATION_DATE',
  ROLE = 'ROLE',
  USER_POSTS = 'USER_POSTS',
  SAVED = 'SAVED',
  SAVE = 'SAVE',
}
