export enum i18Keys {
  CLOSE = 'CLOSE',
  REFRESH_PAGE = 'REFRESH_PAGE',
}

export enum i18KeysHeader {
  MAIN_PAGE = 'MAIN_PAGE',
  ABOUT_PROJECT = 'ABOUT_PROJECT',
  PROFILE = 'PROFILE',
  TAGS = 'TAGS',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
}

export enum i18Tags {
  ANIMALS = 'ANIMALS',
  HUMOR = 'HUMOR',
  TECHNOLOGIES = 'TECHNOLOGIES',
}
